## Acesso aos dados 

Lendo o arquivo e formas de mostrar a tabela

In [2]:
import pandas as pd

df = pd.read_csv("pokemon_data.csv")
display(df)

# display(df.columns)  # mostra o nome das colunas da tabela
# display(df.head(3))  # mostra os primeiros 3 dados da tabela
# display(df.tail(2))  # mostra os últimos 2 dados da tabela

,#,Nome,Tipo 1,Tipo 2,Vida,Ataque,Defensa,Atq Esp,Def Esp,Velocidade,Geracao,Lendario
0,1,Bulbasaur,Planta,Venenoso,45,49,49,65,65,45,1,False
1,2,Ivysaur,Planta,Venenoso,60,62,63,80,80,60,1,False
2,3,Venusaur,Planta,Venenoso,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Planta,Venenoso,80,100,123,122,120,80,1,False
4,4,Charmander,Fogo,NaN,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Pedra,Fada,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Pedra,Fada,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psiquico,Fantasma,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psiquico,Noturno,80,160,60,170,130,80,6,True
799,721,Volcanion,Fogo,Agua,80,110,120,130,90,70,6,True

Acessando colunas individuais

In [3]:
# df['Nome']
# df[['Nome', 'Tipo 1']]  # acessando mais de uma coluna
df[['Nome', 'Tipo 1']][0:150:2]  # do 1º até o 150º pulando de 2 em 2

                          Nome    Tipo 1
0                    Bulbasaur    Planta
2                     Venusaur    Planta
4                   Charmander      Fogo
6                    Charizard      Fogo
8    CharizardMega Charizard Y      Fogo
..                         ...       ...
140                   Gyarados      Agua
142                     Lapras      Agua
144                      Eevee    Normal
146                    Jolteon  Electric
148                    Porygon    Normal

[75 rows x 2 columns]

Acessando linhas individuais

In [4]:
df.iloc[:4]  # do começo até o 3

,#,Nome,Tipo 1,Tipo 2,Vida,Ataque,Defensa,Atq Esp,Def Esp,Velocidade,Geracao,Lendario
0,1,Bulbasaur,Planta,Venenoso,45,49,49,65,65,45,1,False
1,2,Ivysaur,Planta,Venenoso,60,62,63,80,80,60,1,False
2,3,Venusaur,Planta,Venenoso,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Planta,Venenoso,80,100,123,122,120,80,1,False

Acessando linhas e colunas individuais

In [5]:
df.iloc[2, 1]  #  coluna 1, posição 2

'Venusaur'

Buscando por uma informação específica

In [6]:
df.loc[df['Tipo 1'] == 'Fogo']

,#,Nome,Tipo 1,Tipo 2,Vida,Ataque,Defensa,Atq Esp,Def Esp,Velocidade,Geracao,Lendario
4,4,Charmander,Fogo,NaN,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fogo,NaN,58,64,58,80,65,80,1,False
6,6,Charizard,Fogo,Voador,78,84,78,109,85,100,1,False
7,6,CharizardMega Charizard X,Fogo,Dragao,78,130,111,130,85,100,1,False
8,6,CharizardMega Charizard Y,Fogo,Voador,78,104,78,159,115,100,1,False
42,37,Vulpix,Fogo,NaN,38,41,40,50,65,65,1,False
43,38,Ninetales,Fogo,NaN,73,76,75,81,100,100,1,False
63,58,Growlithe,Fogo,NaN,55,70,45,70,50,60,1,False
64,59,Arcanine,Fogo,NaN,90,110,80,100,80,95,1,False
83,77,Ponyta,Fogo,NaN,50,85,55,65,65,90,1,False
84,78,Rapidash,Fogo,NaN,65,100,70,80,80,105,1,False
135,126,Magmar,Fogo,NaN,65,95,57,100,85,93,1,False
147,136,Flareon,Fogo,NaN,65,130,60,95,110,65,1,False
158,146,Moltres,Fogo,Voador,90,100,90,125,85,90,1,True
169,155,Cyndaquil,Fogo,NaN,39,52,43,60,50,65,2,False
170,156,Quilava,Fogo,NaN,58,64,58,80,65,80,2,False
171,157,Typhlosion,Fogo,NaN,78,84,78,109,85,100,2,False
236,218,Slugma,Fogo,NaN,40,40,40,70,40,20,2,False
237,219,Magcargo,Fogo,Pedra,50,50,120,80,80,30,2,False
259,240,Magby,Fogo,NaN,45,75,37,70,55,83,2,False
263,244,Entei,Fogo,NaN,115,115,85,90,75,100,2,True
270,250,Ho-oh,Fogo,Voador,106,130,90,110,154,90,2,True
276,255,Torchic,Fogo,NaN,45,60,40,70,50,45,3,False
277,256,Combusken,Fogo,Lutador,60,85,60,85,60,55,3,False
278,257,Blaziken,Fogo,Lutador,80,120,70,110,70,80,3,False
279,257,BlazikenMega Blaziken,Fogo,Lutador,80,160,80,130,80,100,3,False
352,322,Numel,Fogo,Terra,60,60,40,65,45,35,3,False
353,323,Camerupt,Fogo,Terra,70,100,70,105,75,40,3,False
354,323,CameruptMega Camerupt,Fogo,Terra,70,120,100,145,105,20,3,False
355,324,Torkoal,Fogo,NaN,70,85,140,85,70,20,3,False
435,390,Chimchar,Fogo,NaN,44,58,44,58,44,61,4,False
436,391,Monferno,Fogo,Lutador,64,78,52,78,52,81,4,False
437,392,Infernape,Fogo,Lutador,76,104,71,104,71,108,4,False
518,467,Magmortar,Fogo,NaN,75,95,67,125,95,83,4,False
542,485,Heatran,Fogo,Metalico,91,90,106,130,106,77,4,True
557,498,Tepig,Fogo,NaN,65,63,45,45,45,45,5,False
558,499,Pignite,Fogo,Lutador,90,93,55,70,55,55,5,False
559,500,Emboar,Fogo,Lutador,110,123,65,100,65,65,5,False
572,513,Pansear,Fogo,NaN,50,53,48,53,48,64,5,False
573,514,Simisear,Fogo,NaN,75,98,63,98,63,101,5,False
614,554,Darumaka,Fogo,NaN,70,90,45,15,45,50,5,False
615,555,DarmanitanStandard Mode,Fogo,NaN,105,140,55,30,55,95,5,False
616,555,DarmanitanZen Mode,Fogo,Psiquico,105,30,105,140,105,55,5,False
692,631,Heatmor,Fogo,NaN,85,97,66,105,66,65,5,False
721,653,Fennekin,Fogo,NaN,40,45,40,62,60,60,6,False
722,654,Braixen,Fogo,NaN,59,59,58,90,70,73,6,False
723,655,Delphox,Fogo,Psiquico,75,69,72,114,100,104,6,False
730,662,Fletchinder,Fogo,Voador,62,73,55,56,52,84,6,False
731,663,Talonflame,Fogo,Voador,78,81,71,74,69,126,6,False
735,667,Litleo,Fogo,Normal,62,50,58,73,54,72,6,False
736,668,Pyroar,Fogo,Normal,86,68,72,109,66,106,6,False
799,721,Volcanion,Fogo,Agua,80,110,120,130,90,70,6,True

Acessando as linhas por nome

In [7]:
for indice, linha in df.iterrows():
    print(indice, linha['Nome'])
    if indice == 150:  # if linha['#'] == 150: 
        break

0 Bulbasaur
1 Ivysaur
2 Venusaur
3 VenusaurMega Venusaur
4 Charmander
5 Charmeleon
6 Charizard
7 CharizardMega Charizard X
8 CharizardMega Charizard Y
9 Squirtle
10 Wartortle
11 Blastoise
12 BlastoiseMega Blastoise
13 Caterpie
14 Metapod
15 Butterfree
16 Weedle
17 Kakuna
18 Beedrill
19 BeedrillMega Beedrill
20 Pidgey
21 Pidgeotto
22 Pidgeot
23 PidgeotMega Pidgeot
24 Rattata
25 Raticate
26 Spearow
27 Fearow
28 Ekans
29 Arbok
30 Pikachu
31 Raichu
32 Sandshrew
33 Sandslash
34 Nidoran (Female)
35 Nidorina
36 Nidoqueen
37 Nidoran (Male)
38 Nidorino
39 Nidoking
40 CleFada
41 Clefable
42 Vulpix
43 Ninetales
44 Jigglypuff
45 Wigglytuff
46 Zubat
47 Golbat
48 Oddish
49 Gloom
50 Vileplume
51 Paras
52 Parasect
53 Venonat
54 Venomoth
55 Diglett
56 Dugtrio
57 Meowth
58 Persian
59 Psyduck
60 Golduck
61 Mankey
62 Primeape
63 Growlithe
64 Arcanine
65 Poliwag
66 Poliwhirl
67 Poliwrath
68 Abra
69 Kadabra
70 Alakazam
71 AlakazamMega Alakazam
72 Machop
73 Machoke
74 Machamp
75 Bellsprout
76 Weepinbell
77 Victreebel
78 Tentacool
79 Tentacruel
80 Geodude
81 Graveler
82 Golem
83 Ponyta
84 Rapidash
85 Slowpoke
86 Slowbro
87 SlowbroMega Slowbro
88 Magnemite
89 Magneton
90 Farfetch'd
91 Doduo
92 Dodrio
93 Seel
94 Dewgong
95 Grimer
96 Muk
97 Shellder
98 Cloyster
99 Gastly
100 Haunter
101 Gengar
102 GengarMega Gengar
103 Onix
104 Drowzee
105 Hypno
106 Krabby
107 Kingler
108 Voltorb
109 Electrode
110 Exeggcute
111 Exeggutor
112 Cubone
113 Marowak
114 Hitmonlee
115 Hitmonchan
116 Lickitung
117 Koffing
118 Weezing
119 Rhyhorn
120 Rhydon
121 Chansey
122 Tangela
123 Kangaskhan
124 KangaskhanMega Kangaskhan
125 Horsea
126 Seadra
127 Goldeen
128 Seaking
129 Staryu
130 Starmie
131 Mr. Mime
132 Scyther
133 Jynx
134 Electabuzz
135 Magmar
136 Pinsir
137 PinsirMega Pinsir
138 Tauros
139 Magikarp
140 Gyarados
141 GyaradosMega Gyarados
142 Lapras
143 Ditto
144 Eevee
145 Vaporeon
146 Jolteon
147 Flareon
148 Porygon
149 Omanyte
150 Omastar

Valores estatísticos básicos

In [8]:
df.describe()

,#,Vida,Ataque,Defensa,Atq Esp,Def Esp,Velocidade,Geracao
count,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.00000
mean,362.813750,69.258750,79.001250,73.842500,72.820000,71.902500,68.277500,3.32375
std,208.343798,25.534669,32.457366,31.183501,32.722294,27.828916,29.060474,1.66129
min,1.000000,1.000000,5.000000,5.000000,10.000000,20.000000,5.000000,1.00000
25%,184.750000,50.000000,55.000000,50.000000,49.750000,50.000000,45.000000,2.00000
50%,364.500000,65.000000,75.000000,70.000000,65.000000,70.000000,65.000000,3.00000
75%,539.250000,80.000000,100.000000,90.000000,95.000000,90.000000,90.000000,5.00000
max,721.000000,255.000000,190.000000,230.000000,194.000000,230.000000,180.000000,6.00000